grafana:
  namespace: teste
  nodeSelectorEnabled: false
  nodePoolName: ""
  config:
    url: "192.168.0.10"
    serve_from_subpath: true
    timezone: "browser"
  dashboards:
    loki: true
    metrics: false
  lokiConfig:
    address: loki
    port: 3100
  ingress:
    annotations:
      konghq.com/strip-path: "true"
    ingressClass: kong
    path: /grafana
    host: ""
