apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragnarok.fullname" . }}-char-server
  labels:
    {{- include "ragnarok.charServer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ragnarok.charServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.charServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ragnarok.charServer.labels" . | nindent 8 }}
        {{- with .Values.charServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.charServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.charServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.charServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.charServer.image.repository }}:{{ .Values.charServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.charServer.image.pullPolicy }}
          command: ["/rathena/char-server"]
          ports:
            - name: http
              containerPort: {{ .Values.charServer.service.port }}
              protocol: TCP
          {{- with .Values.charServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.charServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.charServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.charServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.charServer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.charServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.charServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.charServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
