apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragnarok.fullname" . }}-char-server
  labels:
    {{- include "ragnarok.charServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.charServer.service.type }}
  ports:
    - port: {{ .Values.charServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ragnarok.charServer.selectorLabels" . | nindent 4 }}
