apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragnarok.fullname" . }}-conf
  labels:
    {{- include "ragnarok.charServer.labels" . | nindent 4 }}
data:
  inter_conf.txt: |
    char_server_ip: ragnarok-db-mysql
    char_server_port: 3306
    char_server_id: ragnarok
    char_server_pw: ragnarok123
    char_server_db: ragnarok
    
    login_server_ip: ragnarok-db-mysql
    login_server_port: 3306
    login_server_id: ragnarok
    login_server_pw: ragnarok123
    login_server_db: ragnarok
    
    ipban_db_ip: ragnarok-db-mysql
    ipban_db_port: 3306
    ipban_db_id: ragnarok
    ipban_db_pw: ragnarok123
    ipban_db_db: ragnarok
    
    map_server_ip: ragnarok-db-mysql
    map_server_port: 3306
    map_server_id: ragnarok
    map_server_pw: ragnarok123
    map_server_db: ragnarok
    // MySQL Web Server
    web_server_ip: ragnarok-db-mysql
    web_server_port: 3306
    web_server_id: ragnarok
    web_server_pw: ragnarok123
    web_server_db: ragnarok

    // MySQL Log Database
    log_db_ip: ragnarok-db-mysql
    log_db_port: 3306
    log_db_id: ragnarok
    log_db_pw: ragnarok123
    log_db_db: ragnarok
  
  char_conf.txt: |
    server_name: dodoRO
    userid: dfvneto
    passwd: neto123b
    login_ip: ragnarok-login-server
  map_conf.txt: |
    char_ip: ragnarok-char-server
    userid: dfvneto
    passwd: neto123b

  char_athena.txt: |
    userid: dfvneto
    passwd: neto123b
  
  map_athena.txt: |
    userid: dfvneto
    passwd: neto123b
