apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragnarok.fullname" . }}-login-server
  labels:
    {{- include "ragnarok.loginServer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ragnarok.loginServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.loginServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ragnarok.loginServer.labels" . | nindent 8 }}
        {{- with .Values.loginServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.loginServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.loginServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.loginServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.loginServer.image.repository }}:{{ .Values.loginServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.loginServer.image.pullPolicy }}
          command: ["/rathena/login-server"]
          ports:
            - name: http
              containerPort: {{ .Values.loginServer.service.port }}
              protocol: TCP
          {{- with .Values.loginServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.loginServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.loginServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.loginServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.loginServer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loginServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loginServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.loginServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
