apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragnarok.fullname" . }}-login-server
  labels:
    {{- include "ragnarok.loginServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loginServer.service.type }}
  ports:
    - port: {{ .Values.loginServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ragnarok.loginServer.selectorLabels" . | nindent 4 }}
