apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragnarok.fullname" . }}-map-server
  labels:
    {{- include "ragnarok.mapServer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ragnarok.mapServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mapServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ragnarok.mapServer.labels" . | nindent 8 }}
        {{- with .Values.mapServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.mapServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.mapServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.mapServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.mapServer.image.repository }}:{{ .Values.mapServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mapServer.image.pullPolicy }}
          command: ["/rathena/map-server"]
          ports:
            - name: http
              containerPort: {{ .Values.mapServer.service.port }}
              protocol: TCP
          {{- with .Values.mapServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mapServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mapServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mapServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.mapServer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mapServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mapServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mapServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
