apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragnarok.fullname" . }}-map-server
  labels:
    {{- include "ragnarok.mapServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mapServer.service.type }}
  ports:
    - port: {{ .Values.mapServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ragnarok.mapServer.selectorLabels" . | nindent 4 }}
