services:
    database:
        image: "docker.io/bitnami/mysql:9.3.0-debian-12-r0"
        container_name: "database"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "./rathenadb:/var/lib/mysql" # save database to local disk
            - "./sql/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok123

    login:
        image: "ragnarok:20220406"
        container_name: "rathena-login"
        command: "/rathena/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "./conf/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./conf/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./conf/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        depends_on:
            - database
    char:
        image: "ragnarok:20220406"
        container_name: "rathena-char"
        command: "/rathena/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "./conf/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./conf/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./conf/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        depends_on:
            - login
    map:
        image: "ragnarok:20220406"
        container_name: "rathena-map"
        command: "/rathena/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "./conf/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
            - "./conf/char_conf.txt:/rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./conf/map_conf.txt:/rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        depends_on:
            - char

volumes:
    rathenadb:
