services:
    rathenadb:
        image: "mariadb:bionic"
        container_name: "database"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "./rathenadb:/var/lib/mysql" # save database to local disk
            - "./sql/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok123
