{{- range .Values.kongPlugins.consumers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .username }}-key-auth
  labels:
    konghq.com/credential: key-auth
stringData:
  key: {{ .key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .username }}-acl
  labels:
    konghq.com/credential: acl
stringData:
  kongCredType: acl
  group: {{ .group }}
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ .username }}
  annotations:
    kubernetes.io/ingress.class: kong
username: {{ .username }}
credentials:
- {{ .username }}-key-auth
- {{ .username }}-acl
---
{{- end}}
