apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "false"
config:
  origins:
  {{- toYaml $.Values.kongPlugins.corsOrigins | nindent 4 }}
  methods:
  - GET
  - HEAD
  - PUT
  - PATCH
  - POST
  - DELETE
  - OPTIONS
  - TRACE
  - CONNECT
  credentials: false
  exposed_headers: null
  headers: null
  max_age: null
  preflight_continue: false
plugin: cors