apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
config:
  anonymous: null
  hide_credentials: false
  key_in_body: false
  key_in_header: true
  key_in_query: true
  key_names:
  - apikey
  run_on_preflight: true
plugin: key-auth
