apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: response-transformer-web-plugin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "false"
config:
  {{- if .Values.kongPlugins.headersWeb }}
  add:
    headers:
    {{- range .Values.kongPlugins.headersWeb }}
    - {{ . | quote}}
    {{- end}}
  {{- end }}
plugin: response-transformer
