apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana

    app.kubernetes.io/version: 9.5.3
  name: grafana-datasources
  namespace: {{ .Values.grafana.namespace }}
stringData:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
      - name: loki
        type: loki
        access: proxy
        orgId: 1
        url: http://{{ .Values.grafana.lokiConfig.address }}:{{ .Values.grafana.lokiConfig.port }}
      
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: '1'

        editable: false
      - name: loki-production
        type: loki
        access: proxy
        # orgId: 2
        url: http://{{ .Values.grafana.lokiConfig.address }}:{{ .Values.grafana.lokiConfig.port }}
      
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'production'

        editable: false
type: Opaque