apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{- toYaml .Values.grafana.ingress.annotations | nindent 4 }}   
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana

    app.kubernetes.io/version: 9.5.3
  name: grafana-ingress
  namespace: {{ .Values.grafana.namespace }}
spec:
  ingressClassName: {{ .Values.grafana.ingress.ingressClass }}
  rules:
    - host: "{{ .Values.grafana.ingress.host }}"
      http:
        paths: 
          - path: {{ .Values.grafana.ingress.path  }}
            pathType: Prefix
            backend:
              service: 
                name: grafana
                port: 
                  name: "http"

          
