apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  settings.yaml: |
   #  base: http://k8scp/home
   #  base: http://host.local/home
   providers:
     longhorn:
       url: http://192.168.0.10/longhorn/
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - GitOps:
        - Argocd:
            href: http://192.168.0.10/argo
            description: argo

    - Metrics:
        - grafana:
            href: http://192.168.0.10/grafana/
            description: grafana

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - longhorn:
        # Show the expanded view
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
        # An explicit list of nodes to show. All are shown by default if "nodes" is true
        include:
          - node1
  docker.yaml: ""