charServer:
  image:
    repository: ragnarok
    pullPolicy: Never
    tag: "latest"

  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}
  service:
    type: ClusterIP
    port: 6121

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.latest
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  volumes:
    - name: inter-config
      configMap:
        name: ragnarok-conf
    - name: char-config
      configMap:
        name: ragnarok-conf
    - name: map-config
      configMap:
        name: ragnarok-conf
  volumeMounts:
    - mountPath: /rathena/conf/import/inter_conf.txt
      name: inter-config
      subPath: inter_conf.txt
    - mountPath: /rathena/conf/import/char_conf.txt
      name: char-config
      subPath: char_conf.txt
    - mountPath: /rathena/conf/import/map_conf.txt
      name: map-config
      subPath: map_conf.txt
    - mountPath: /rathena/conf/import/map_athena.txt
      name: map-config
      subPath: map_athena.txt
    - mountPath: /rathena/conf/import/char_athena.txt
      name: map-config
      subPath: char_athena.txt
  nodeSelector: {}

  tolerations: []

  affinity: {}

loginServer:
  image:
    repository: ragnarok
    pullPolicy: IfNotPresent
    tag: "latest"
  imagePullSecrets: []

  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 6900

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.latest
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  volumes:
    - name: inter-config
      configMap:
        name: ragnarok-conf
    - name: char-config
      configMap:
        name: ragnarok-conf
    - name: map-config
      configMap:
        name: ragnarok-conf
  volumeMounts:
    - mountPath: /rathena/conf/import/inter_conf.txt
      name: inter-config
      subPath: inter_conf.txt
    - mountPath: /rathena/conf/import/char_conf.txt
      name: char-config
      subPath: char_conf.txt
    - mountPath: /rathena/conf/import/map_conf.txt
      name: map-config
      subPath: map_conf.txt
    - mountPath: /rathena/conf/import/map_athena.txt
      name: map-config
      subPath: map_athena.txt
    - mountPath: /rathena/conf/import/char_athena.txt
      name: map-config
      subPath: char_athena.txt
  nodeSelector: {}
  tolerations: []
  affinity: {}

mapServer:
  image:
    repository: ragnarok
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5121

  ingress:
    enabled: false
    className: ""
    annotations: {}

    hosts:
      - host: chart-example.latest
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  volumes:
    - name: inter-config
      configMap:
        name: ragnarok-conf
    - name: char-config
      configMap:
        name: ragnarok-conf
    - name: map-config
      configMap:
        name: ragnarok-conf
  volumeMounts:
    - mountPath: /rathena/conf/import/inter_conf.txt
      name: inter-config
      subPath: inter_conf.txt
    - mountPath: /rathena/conf/import/char_conf.txt
      name: char-config
      subPath: char_conf.txt
    - mountPath: /rathena/conf/import/map_conf.txt
      name: map-config
      subPath: map_conf.txt
    - mountPath: /rathena/conf/import/map_athena.txt
      name: map-config
      subPath: map_athena.txt
    - mountPath: /rathena/conf/import/char_athena.txt
      name: map-config
      subPath: char_athena.txt
  nodeSelector: {}
  tolerations: []
  affinity: {}
